## Before attempting to run please provide a workspace-scoped API Token in the `api_token` variable. 
# You can generate this from the Hub website: https://prod.eodatahub.org.uk/workspaces/, making sure to 
# select the correct workspace, as you have configured below in the `workspace` variable.

@api_token = <your-token>

@scheme = https
@ades = prod.eodatahub.org.uk/api/catalogue/stac
@workspaces_prefix=catalogs/user/catalogs
@workspace = <workspace-name>

@deployStatus = {{deployProcessJson.response.headers.Location}}
@executeStatus = {{executeProcess.response.headers.Location}}

###

# @name deleteProcess
DELETE {{scheme}}://{{ades}}/{{workspaces_prefix}}/{{workspace}}/processes/convert-stac HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name listProcesses
GET {{scheme}}://{{ades}}/{{workspaces_prefix}}/{{workspace}}/processes HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name deployProcessJson
POST {{scheme}}://{{ades}}/{{workspaces_prefix}}/{{workspace}}/processes HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json
Content-Type: application/json

{
  "executionUnit": {
    "href": "https://raw.githubusercontent.com/EO-DataHub/eodhp-ades-demonstration/refs/heads/main/convert-url-app.cwl",
    "type": "application/cwl"
  }
}

###

# @name getDeployStatus
GET {{deployStatus}} HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name getProcessDetails
GET {{scheme}}://{{ades}}/{{workspaces_prefix}}/{{workspace}}/processes/convert-stac HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name executeProcess
POST {{scheme}}://{{ades}}/{{workspaces_prefix}}/{{workspace}}/processes/convert-url/execution HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json
Content-Type: application/json
Prefer: respond-async

{
  "inputs": {
      "fn": "resize",
      "url":  "https://raw.githubusercontent.com/EO-DataHub/eodhp-ades-demonstration/refs/heads/main/DataHub-Logo.PNG",
      "size": "50%"
  }
}

###

# @name getExecuteStatus
GET {{executeStatus}} HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###


# @name getProcessingResults
GET {{executeStatus}}/results HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name undeployProcess
DELETE {{scheme}}://{{ades}}/{{workspaces_prefix}}/{{workspace}}/processes/convert-stac HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name listJobs
GET {{scheme}}://{{ades}}/{{workspace}}/jobs HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name deleteJob
DELETE {{scheme}}://{{ades}}/{{workspace}}/jobs/<jobID> HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name deployProcessCWL
POST {{scheme}}://{{ades}}/{{workspaces_prefix}}/{{workspace}}/processes/ HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json
Content-Type: application/cwl+yaml

< convert-url-app.cwl

