## Before attempting to run please provide the user and password login details for the ADES endpoint

@logindetails=user:password 

@scheme = https
@ades = ades.test.eodhp.eco-ke-staging.com
@username=eric

@deployStatus = {{deployProcessJson.response.headers.Location}}
@executeStatus = {{executeProcess.response.headers.Location}}

###

# @name deleteProcess
DELETE {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/convert-stac HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###

# @name listProcesses
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###

# @name deployProcessJson
POST {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json
Content-Type: application/json

{
  "executionUnit": {
    "href": "https://raw.githubusercontent.com/EOEPCA/deployment-guide/main/deploy/samples/requests/processing/convert-stac-app.cwl",
    "type": "application/cwl"
  }
}

###

# @name getDeployStatus
GET {{deployStatus}} HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###

# @name getProcessDetails
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/convert-stac HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###

# @name executeProcess
POST {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/convert-stac/execution HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json
Content-Type: application/json
Prefer: respond-async

{
  "inputs": {
      "fn": "resize",
      "stac":  "https://raw.githubusercontent.com/EOEPCA/convert/main/stac/eoepca-logo.json",
      "size": "50%"
  }
}

###

# @name getExecuteStatus
GET {{executeStatus}} HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###


# @name getProcessingResults
GET {{executeStatus}}/results HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###

# @name undeployProcess
DELETE {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/convert-stac HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###

# @name listJobs
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/jobs HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###

# @name deployProcessCWL
POST {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json
Content-Type: application/cwl+yaml

< convert-stac-app.cwl

