## Before attempting to run please provide a workspace-scoped API Token in the `api_token` variable. 
# You can generate this from the Hub website: https://prod.eodatahub.org.uk/workspaces/, making sure to 
# select the correct workspace, as you have configured below in the `workspace` variable.

@api_token = <your-token>

@scheme = https
@ades = prod.eodatahub.org.uk/api/catalogue/stac
@workspaces_prefix=catalogs/user/catalogs
@workspace = <workspace-name>

@deployStatus = {{deployProcessJson.response.headers.Location}}
@executeStatus = {{executeProcess.response.headers.Location}}

###

# @name deleteProcess
DELETE {{scheme}}://{{ades}}/{{workspace}}/{{workspaces_prefix}}/processes/water-bodies HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name listProcesses
GET {{scheme}}://{{ades}}/{{workspaces_prefix}}/{{workspace}}/processes/ HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name deployProcessJson
POST {{scheme}}://{{ades}}/{{workspaces_prefix}}/{{workspace}}/processes/ HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json
Content-Type: application/json

{
  "executionUnit": {
    "href": "https://raw.githubusercontent.com/EO-DataHub/eodhp-ades-demonstration/refs/heads/main/water-bodies-app.cwl",
    "type": "application/cwl"
  }
}

###

# @name getDeployStatus
GET {{deployStatus}} HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name getProcessDetails
GET {{scheme}}://{{ades}}/{{workspaces_prefix}}/{{workspace}}/processes/water-bodies HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name executeProcess
POST https://{{ades}}/{{workspaces_prefix}}/{{workspace}}/processes/water-bodies/execution HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json
Content-Type: application/json
Prefer: respond-async

{
  "inputs": {
    "workspace": "{{workspace}}",
    "stac_items": [
      "https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_10TFK_20210713_0_L2A",
      "https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_10TFK_20220524_0_L2A"
    ],
    "aoi": "-121.399,39.834,-120.74,40.472",
    "epsg": "EPSG:4326",
    "bands": [
      "green",
      "nir"
    ]
  }
}

###
## Using resources from our own EO Data Hub Resource Catalogue
# @name executeProcess
POST https://{{ades}}/{{workspaces_prefix}}/{{workspace}}/processes/water-bodies/execution HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json
Content-Type: application/json
Prefer: respond-async

{
  "inputs": {
    "stac_items": [
      "https://test.eodatahub.org.uk/api/catalogue/stac/catalogs/supported-datasets/earth-search-aws/collections/sentinel-2-c1-l2a/items/S2B_T42MVU_20240319T054135_L2A"     
    ],
    "aoi": "68.09, -6.42, 69.09, -5.43",
    "epsg": "EPSG:4326",
    "bands": [
      "green",
      "nir"
    ]
  }
}

###

# @name getExecuteStatus
GET {{executeStatus}} HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###


# @name getProcessingResults
GET {{executeStatus}}/results HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name undeployProcess
DELETE {{scheme}}://{{ades}}/{{workspaces_prefix}}/{{workspace}}/processes/water-bodies HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name listJobs
GET {{scheme}}://{{ades}}/{{workspace}}/jobs HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name deleteJob
DELETE {{scheme}}://{{ades}}/{{workspace}}/jobs/<jobID> HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json

###

# @name deployProcessCWL
POST {{scheme}}://{{ades}}/{{workspaces_prefix}}/{{workspace}}/processes/ HTTP/1.1
Authorization: Bearer {{api_token}}
Accept: application/json
Content-Type: application/cwl+yaml

< water-bodies-app.cwl

